module.exports={
    options:{
        cache:false
    },
    dist:{
        files:[{
            expand:true,
            cwd:'images/',
            src:['*.*'],
            dest:'dist/'
        }]
    }
}